site_name: "Manipulaci贸 de documents web: Javascript"

nav:
  - "Inici": 'index.md'
  - "1. Introducci贸. JavaScript en entorns client": '1.intro.md'
  - "2. El DOM": '2.dom.md'
  - "3. Gesti贸 d'esdeveniments": '3.events.md'
  - "4. Gesti贸 de formularis HTML amb JS": '4.forms.md'
  
theme:
  name: 'material'
  custom_dir: 'overrides'
  logo: 'img/logo.svg'
  favicon: 'img/logo.svg'
  features:
    - content.code.copy # PEr copiar codi
  palette:
    accent: deep purple
    primary: amber


extra_css:
  - https://joamuran.net/curs24_25/css/material-just.css

plugins:
  - search
  - glightbox   # Per vore les imatges en gran quan fas clic en elles.
  # - pandoc

markdown_extensions:
  - attr_list           # Permet incorporar atributs a les imatges { width=100px }
  - md_in_html # Junt a attr_list per afegir peus a les imatges
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      baselevel: 2
      toc_depth: 3